### ISSUE TITLE
Please commit Cargo.lock

### ISSUE THREAD

**Issue by spwhitton** [sudipghimire533/ytui-music#18]
https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

Thanks for the cool project.

**Comment by sudipghimire533** [comment]
Thanks for reminder mate. Here it is: https://github.com/sudipghimire533/ytui-music/commit/b639c344bbcaae1c943c36263be79a869f585ba1
