### ISSUE TITLE
YTUI cant find audio directory

### ISSUE THREAD

**Issue by ObsidianRavenGlass** [sudipghimire533/ytui-music#20]
"ytui_music run" spits out this error 

Ytui was unable to find the audio directory.You can try re-run by setting YTUI_MUSIC_DIR variable or downloading the template config file.

There probably is an easy solution, but I don't know where to start.

**Comment by sudipghimire533** [comment]
From ytui-music, you can download the songs for offline. For that you would need to specify where to download those.

What os are you using?
Make sure this directory exists ( if not create them )
- Mac:  `/Users/Alice/Music`
- Windows: `C:\Users\Alice\Music`
- Linux:  `/home/alice/Music`

Or if you want to use another directory run like:
```
YTUI_MUSIC_DIR="/custom/music/path" ytui_music run
```

**Comment by ObsidianRavenGlass** [comment]
Ran the command and it worked. It didn't find the music folder for whatever reason, though.
