### ISSUE TITLE
add libmpv-dev to the dependencies to the readme.

### ISSUE THREAD

**Issue by Sanix-Darker** [sudipghimire533/ytui-music#29]
when trying to build the app, i got a weird error with missing `-lmpv` which I fixed by installing `libmpv-dev`, am on ubuntu btw.
If this sound good for you I will make a small PR for it too.

**Comment by sudipghimire533** [comment]
I would be happy to merge your PR

**Comment by Sanix-Darker** [comment]
The PR : #30 @sudipghimire533
