### ISSUE TITLE
Cant run Ytui-music

### ISSUE THREAD

**Issue by arturbred** [sudipghimire533/ytui-music#39]
Hi, I'm new to linux, using Linux Mint, VERSION=21.2 (Victoria), I followed the instructions but when I try to run de binary file I get stuck here:
![image](https://github.com/sudipghimire533/ytui-music/assets/144156050/d5604582-994d-42b8-8f2e-8f76f306f8dc)

What am i missing?

**Comment by sudipghimire533** [comment]
you should run `./ytui_music run`

**Comment by arturbred** [comment]
Tks man! It worked! Sorry for the noob question. :)
