### ISSUE TITLE
the ytui_music binary fails to be compiled by cargo

### ISSUE THREAD

**Issue by Vjay15** [sudipghimire533/ytui-music#42]
![image](https://github.com/sudipghimire533/ytui-music/assets/65224022/5e244fe5-f585-46f8-a4c6-8367d35b4321)
here is the image of the error i got have no idea what to do i tried to fix it by doing what it said but that didnt work either :(

**Comment by NineXYZ** [comment]
I don't know if this could fix your problem but I had to install this before compiling.
(This are the names for fedora38)
mpv-devel
openssl-devel

**Comment by Vjay15** [comment]
> 

nope didnt work i only didnt have mpv-devel and i installed, despite that it still raises the same error also
![image](https://github.com/sudipghimire533/ytui-music/assets/65224022/bb2a24f6-8568-41d3-8226-105f7e1b947a)
now has the binary but it doesnt even work ;-;

**Comment by sudipghimire533** [comment]
You have to run `./ytui_music` remember to put `./` before.

**Comment by PiTiKiDBB** [comment]
What is the solution? Im having the same error.

**Comment by sudipghimire533** [comment]
It\s to run with `./ytui_music run`

**Comment by chokgok** [comment]
> It\s to run with `./ytui_music run`

You know that this error is not solved/closed, right? I have the same problem with compiling. It does not compile due to a missing library (I believe).

```
note: /usr/bin/ld: cannot find -lmpv: No such file or directory
```

Because of this error, I cannot compile this software. I run a generic WSL instance of Ubuntu 22.04.3 LTS.
I installed mpv and mpd packages, because they seem related to the error, but I have no luck.

**Comment by chokgok** [comment]
Alright I figured it out on Ubuntu (and maybe Debian).

```
sudo apt install libmpv-dev
```

Install this and the compilation will work.
